name: Flutter Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ai-pro-analyzer  # <--- EZ A LÉNYEG: IDE ÍRD BE A MAPPA NEVÉT!
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: ai-pro-analyzer/build/app/outputs/flutter-apk/app-release.apk
